[project]
name = "irc-hand"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "earthengine-api>=1.5.1",
    "geopandas>=1.0.1",
    "geopy>=2.4.1",
    "pandas>=2.2.3",
    "shapely>=2.0.7",
]
